"""add project gallery

Revision ID: 56a00a82ddcc
Revises: 442306f9c2b3
Create Date: 2026-05-26 20:03:38.643956
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '56a00a82ddcc'
down_revision: Union[str, None] = '442306f9c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Empty JSON array as the default for existing rows.
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'gallery',
                sa.JSON(),
                nullable=False,
                server_default=sa.text("'[]'"),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('gallery')

    # ### end Alembic commands ###
